-- MySQL Script generated by MySQL Workbench
-- Ter 22 Mai 2018 09:30:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tip_usuario` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`montadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montadora` (
  `idmontadora` INT NOT NULL,
  `montadora` VARCHAR(45) NULL,
  PRIMARY KEY (`idmontadora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmodelo` INT NOT NULL,
  `nome_modelo` VARCHAR(45) NULL,
  `montadora_idmontadora` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `fk_modelo_montadora1_idx` (`montadora_idmontadora` ASC),
  CONSTRAINT `fk_modelo_montadora1`
    FOREIGN KEY (`montadora_idmontadora`)
    REFERENCES `mydb`.`montadora` (`idmontadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_ano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_ano` (
  `idveiculo` INT NOT NULL,
  `ano` VARCHAR(45) NULL,
  `potencia` VARCHAR(45) NULL,
  `portas` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `comprimento` VARCHAR(45) NULL,
  `largura` VARCHAR(45) NULL,
  `cambio` VARCHAR(45) NULL,
  `velocidade` VARCHAR(45) NULL,
  `tanque_combustivel` VARCHAR(45) NULL,
  `tip_combustivel` VARCHAR(45) NULL,
  `porta_malas` VARCHAR(45) NULL,
  `tip_direcao` VARCHAR(45) NULL,
  `consumo_urb` VARCHAR(45) NULL,
  `consumo_rod` VARCHAR(45) NULL,
  `marcha` VARCHAR(45) NULL,
  `tip_tracao` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `ocupantes` VARCHAR(45) NULL,
  `tip_freio` VARCHAR(45) NULL,
  `tip_veiculo` VARCHAR(45) NULL,
  `modelo_idmodelo` INT NOT NULL,
  `like` INT(11) NULL,
  `dislike` INT(11) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_modelo1_idx` (`modelo_idmodelo` ASC),
  INDEX `fk_veiculo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_veiculo_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_modelo` (
  `usuario_idusuario` INT NOT NULL,
  `modelo_idmodelo` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `modelo_idmodelo`),
  INDEX `fk_usuario_has_modelo_modelo1_idx` (`modelo_idmodelo` ASC),
  INDEX `fk_usuario_has_modelo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_modelo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_modelo_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
