insert into montadora (idmontadora, montadora) values ('6','Audi');
insert into montadora (idmontadora, montadora) values ('7','BMW');
insert into montadora (idmontadora, montadora) values ('13','Citroën');
insert into montadora (idmontadora, montadora) values ('21','Fiat');
insert into montadora (idmontadora, montadora) values ('22','Ford');
insert into montadora (idmontadora, montadora) values ('23','GM - Chevrolet');
insert into montadora (idmontadora, montadora) values ('25','Honda');
insert into montadora (idmontadora, montadora) values ('26','Hyundai');
insert into montadora (idmontadora, montadora) values ('31','Kia Motors');
insert into montadora (idmontadora, montadora) values ('39','Mercedes-Benz');
insert into montadora (idmontadora, montadora) values ('41','Mitsubishi');
insert into montadora (idmontadora, montadora) values ('43','Nissan');
insert into montadora (idmontadora, montadora) values ('44','Peugeot');
insert into montadora (idmontadora, montadora) values ('48','Renault');
insert into montadora (idmontadora, montadora) values ('55','Suzuki');
insert into montadora (idmontadora, montadora) values ('56','Toyota');
insert into montadora (idmontadora, montadora) values ('58','Volvo');
insert into montadora (idmontadora, montadora) values ('59','VW - VolksWagen');
insert into montadora (idmontadora, montadora) values ('1','Acura');
insert into montadora (idmontadora, montadora) values ('2','Agrale');
insert into montadora (idmontadora, montadora) values ('3','Alfa Romeo');
insert into montadora (idmontadora, montadora) values ('4','AM Gen');
insert into montadora (idmontadora, montadora) values ('5','Asia Motors');
insert into montadora (idmontadora, montadora) values ('189','ASTON MARTIN');
insert into montadora (idmontadora, montadora) values ('207','Baby');
insert into montadora (idmontadora, montadora) values ('8','BRM');
insert into montadora (idmontadora, montadora) values ('123','Bugre');
insert into montadora (idmontadora, montadora) values ('10','Cadillac');
insert into montadora (idmontadora, montadora) values ('11','CBT Jipe');
insert into montadora (idmontadora, montadora) values ('136','CHANA');
insert into montadora (idmontadora, montadora) values ('182','CHANGAN');
insert into montadora (idmontadora, montadora) values ('161','CHERY');
insert into montadora (idmontadora, montadora) values ('12','Chrysler');
insert into montadora (idmontadora, montadora) values ('14','Cross Lander');
insert into montadora (idmontadora, montadora) values ('15','Daewoo');
insert into montadora (idmontadora, montadora) values ('16','Daihatsu');
insert into montadora (idmontadora, montadora) values ('17','Dodge');
insert into montadora (idmontadora, montadora) values ('147','EFFA');
insert into montadora (idmontadora, montadora) values ('18','Engesa');
insert into montadora (idmontadora, montadora) values ('19','Envemo');
insert into montadora (idmontadora, montadora) values ('20','Ferrari');
insert into montadora (idmontadora, montadora) values ('149','Fibravan');
insert into montadora (idmontadora, montadora) values ('190','FOTON');
insert into montadora (idmontadora, montadora) values ('170','Fyber');
insert into montadora (idmontadora, montadora) values ('199','GEELY');
insert into montadora (idmontadora, montadora) values ('153','GREAT WALL');
insert into montadora (idmontadora, montadora) values ('24','Gurgel');
insert into montadora (idmontadora, montadora) values ('152','HAFEI');
insert into montadora (idmontadora, montadora) values ('27','Isuzu');
insert into montadora (idmontadora, montadora) values ('208','IVECO');
insert into montadora (idmontadora, montadora) values ('177','JAC');
insert into montadora (idmontadora, montadora) values ('28','Jaguar');
insert into montadora (idmontadora, montadora) values ('29','Jeep');
insert into montadora (idmontadora, montadora) values ('154','JINBEI');
insert into montadora (idmontadora, montadora) values ('30','JPX');
insert into montadora (idmontadora, montadora) values ('32','Lada');
insert into montadora (idmontadora, montadora) values ('171','LAMBORGHINI');
insert into montadora (idmontadora, montadora) values ('33','Land Rover');
insert into montadora (idmontadora, montadora) values ('34','Lexus');
insert into montadora (idmontadora, montadora) values ('168','LIFAN');
insert into montadora (idmontadora, montadora) values ('127','LOBINI');
insert into montadora (idmontadora, montadora) values ('35','Lotus');
insert into montadora (idmontadora, montadora) values ('140','Mahindra');
insert into montadora (idmontadora, montadora) values ('36','Maserati');
insert into montadora (idmontadora, montadora) values ('37','Matra');
insert into montadora (idmontadora, montadora) values ('38','Mazda');
insert into montadora (idmontadora, montadora) values ('40','Mercury');
insert into montadora (idmontadora, montadora) values ('167','MG');
insert into montadora (idmontadora, montadora) values ('156','MINI');
insert into montadora (idmontadora, montadora) values ('42','Miura');
insert into montadora (idmontadora, montadora) values ('45','Plymouth');
insert into montadora (idmontadora, montadora) values ('46','Pontiac');
insert into montadora (idmontadora, montadora) values ('47','Porsche');
insert into montadora (idmontadora, montadora) values ('185','RAM');
insert into montadora (idmontadora, montadora) values ('186','RELY');
insert into montadora (idmontadora, montadora) values ('195','Rolls-Royce');
insert into montadora (idmontadora, montadora) values ('49','Rover');
insert into montadora (idmontadora, montadora) values ('50','Saab');
insert into montadora (idmontadora, montadora) values ('51','Saturn');
insert into montadora (idmontadora, montadora) values ('52','Seat');
insert into montadora (idmontadora, montadora) values ('183','SHINERAY');
insert into montadora (idmontadora, montadora) values ('157','smart');
insert into montadora (idmontadora, montadora) values ('125','SSANGYONG');
insert into montadora (idmontadora, montadora) values ('54','Subaru');
insert into montadora (idmontadora, montadora) values ('165','TAC');
insert into montadora (idmontadora, montadora) values ('57','Troller');
insert into montadora (idmontadora, montadora) values ('163','Wake');
insert into montadora (idmontadora, montadora) values ('120','Walk');